name: Automated API Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
          java-version: '21'
          distribution: 'temurin'

    - name: Grant execute permission for Maven wrapper
      run: chmod +x mvnw
      
    - name: Build project
      run: ./mvnw clean package -DskipTests

    - name: Grant execute permission for jar
      run: chmod +x ./target/backend*.jar

    - name: Run jar
      run: java -jar ./target/backend-0.0.1-SNAPSHOT.jar

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install Apidog CLI
      run: npm install -g apidog-cli

    - name: Running Test Scenario
      run: apidog run https://api.apidog.com/api/v1/projects/718868/api-test/ci-config/362724/detail?token=xUUfO7nb2cTGbM1YV69UTD -r html,cli
